/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    Doc: typeof import('./components/Doc.vue')['default']
    InputModal: typeof import('./components/InputModal.vue')['default']
    InputSearch: typeof import('./components/InputSearch.vue')['default']
    JsonRaw: typeof import('./components/JsonRaw.vue')['default']
    JsonTree: typeof import('./components/JsonTree.vue')['default']
    JsonTreeNode: typeof import('./components/JsonTreeNode.vue')['default']
    LeftHeader: typeof import('./components/LeftHeader.vue')['default']
    Panel: typeof import('./components/Panel.vue')['default']
    PresetButton: typeof import('./components/PresetButton.vue')['default']
    RightHeader: typeof import('./components/RightHeader.vue')['default']
    Split: typeof import('./components/Split.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
  }
}
